/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dirlt_java_jni_Main */

#ifndef _Included_com_dirlt_java_jni_Main
#define _Included_com_dirlt_java_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dirlt_java_jni_Main
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dirlt_java_jni_Main_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
