#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

import os
import glob
env=Environment(CPPPATH = ['..'],
                CXXFLAGS = '-W -Wall -g -Werror -Wno-unused-parameter -O2')
env.StaticLibrary('share',Glob('*.cc'))

test_env = env.Clone()
test_env.Append(LIBPATH = ['.'])
test_env.Append(LIBS = ['share',
                        'rt',
                        'pthread'])

for cc in glob.glob('test/*.cc'):
    test_env.Program(os.path.splitext(cc)[0] + '.exe', [cc])

bench_env = env.Clone()
bench_env.Append(CPPPATH = ['.'])
bench_env.Append(LIBPATH = ['.'])
bench_env.Append(LIBS = ['share',
                        'rt',
                        'pthread'])

for cc in glob.glob('bench/*.cc'):
    bench_env.Program(os.path.splitext(cc)[0] + '.exe', [cc])
