#!/bin/bash
set -e

chown -R mysql:mysql /home/mysql/
chmod 700 /home/mysql/

# initialize MySQL data directory
if [ ! -d /home/mysql/mysql ]; then
  echo "Installing database..."
  mysql_install_db --datadir=/home/mysql/ --user=mysql >/dev/null 2>&1

  # start mysql server
  echo "Starting MySQL server..."
  /usr/bin/mysqld_safe 2>&1 &

  # wait for mysql server to start (max 120 seconds)
  timeout=120
  while ! mysqladmin -uroot ping >/dev/null 2>&1
  do
    timeout=$(expr $timeout - 1)
    if [ $timeout -eq 0 ]; then
      echo "Timeout error occurred trying to start MySQL Daemon."
      exit 1
    fi
    sleep 1
  done

  # grant remote access
  echo "Configuring database..."
  echo "GRANT ALL ON *.* TO 'root'@'172.17.%.%' IDENTIFIED BY '' WITH GRANT OPTION;" | mysql -uroot
  echo "GRANT ALL ON *.* TO 'dirlt'@'%' IDENTIFIED BY 'uvw123' WITH GRANT OPTION;" | mysql -uroot
  echo "FLUSH PRIVILEGES;" | mysql -uroot

else
  echo "Starting MySQL server..."
  /usr/bin/mysqld_safe >/dev/null 2>&1 &

fi

echo "Evertying is done"
