#!/usr/bin/env python
# coding:utf-8
# Copyright (C) dirlt

tags = {
    'Accounting': [],
    'Accounting\xa0Education': [],
    'Acoustic': [],
    'Activism': ['Human Rights',
                 'Vegan',
                 'Climate Change',
                 'Feminist',
                 'LGBT',
                 'Animal Rights'],
    'Activism\xa0Roundup': [],
    'Adventist': [],
    'African\xa0American': [],
    'After\xa0Life': [],
    'Agile': [],
    'Agriculture': ['Poultry',
                    'Fishing',
                    'Gardening',
                    'Beekeeping',
                    'Permaculture'],
    'Agriculture\xa0Roundup': [],
    'Alcatraz': [],
    'Alternative': [],
    'Alternative\xa0Health': ['Yoga',
                              'Chiropractic',
                              'Meditation',
                              'Reiki',
                              'Go To Sleep',
                              'Qigong And Tai Chi',
                              'Holistic Health',
                              'Metaphysics',
                              'Hypnosis'],
    'Alternative\xa0Health\xa0Roundup': [],
    'Alternative\xa0Spirituality': ['Astrology',
                                    'Yoga',
                                    'Shamanism',
                                    'Mythology',
                                    'Meditation',
                                    'New Age',
                                    'After Life',
                                    'Angels',
                                    'Paganism',
                                    'Paranormal',
                                    'Spiritual Beings',
                                    'Tarot',
                                    'UFOs',
                                    'Bigfoot',
                                    'Psychic',
                                    'Unitarian Universalist'],
    "Alzheimer's\xa0Disease": [],
    'American\xa0Football': ['New York Giants', 'Washington Redskins'],
    'American\xa0Football\xa0Roundup': [],
    'American\xa0Horror\xa0Story': [],
    'American\xa0Idol': [],
    'Anatomy': [],
    'Anatomy\xa0Education': [],
    'Android': [],
    'Angels': [],
    'Anglican': [],
    'Animals\xa0and\xa0Pets': ['Fish',
                               'Pets',
                               'Cats',
                               'Dogs',
                               'Poultry',
                               'Beekeeping',
                               'Birds',
                               'Animal Rights'],
    'Animal\xa0Rights': [],
    'Animated\xa0Fiction': ['The Simpsons',
                            'Marvel',
                            'Pixar',
                            'Sailormoon',
                            'Transformers',
                            'South Park',
                            'Animation',
                            'DC',
                            'Anime',
                            'Disney',
                            'Naruto',
                            'Pokemon',
                            'Superman',
                            'Batman',
                            'Avatar - The Last Airbender'],
    'Animation': [],
    'Anime': [],
    'Anthropology': [],
    'Anthropology\xa0Education': [],
    'Apostolic': [],
    'Apple': [],
    'App\xa0Business': [],
    'App\xa0Business\xa0Education': [],
    'Arcade\xa0Games': [],
    'Archaeology': [],
    'Archaeology\xa0Education': [],
    'Architecture': [],
    'Architecture\xa0Education': [],
    'Arkansas\xa0Razorbacks': [],
    'Arrow': [],
    'Arsenal\xa0Football\xa0Club': [],
    'Artificial\xa0Intelligence': [],
    'Arts': ['Knitting',
             'Interior Design',
             'Fashion and Beauty',
             'Theater',
             'Painting',
             'Creativity',
             'Graphic Design',
             'Photography',
             'Quilting',
             'Fine Arts',
             'Architecture'],
    'Arts\xa0Roundup': [],
    'Astrology': [],
    'Astronomy': [],
    'Astronomy\xa0Education': [],
    'Atheism': [],
    'Audiobooks': [],
    'Audio\xa0Theater': [],
    'Aussie\xa0Rules': [],
    'Authors': ['Shakespeare', 'J.R.R. Tolkien'],
    'Autism': [],
    'Auto': [],
    'Avatar\xa0-\xa0The\xa0Last\xa0Airbender': [],
    'Aviation': [],
    'Bands': [],
    'Baptist': [],
    'Baseball': ['Fantasy Baseball',
                 'Toronto Blue Jays',
                 'Chicago Cubs'],
    'Baseball\xa0Roundup': [],
    'Basketball': ['NBA', 'Fantasy Basketball'],
    'Basketball\xa0Roundup': [],
    'Batman': [],
    'Battlestar\xa0Galactica': [],
    'Bedtime\xa0Stories': [],
    'Beekeeping': [],
    'Beer': [],
    'Being\xa0Human': [],
    'Better\xa0Call\xa0Saul': [],
    'Bible\xa0Prophecy': [],
    'Bigfoot': [],
    'Big\xa0Brother': [],
    'Biology': [],
    'Biology\xa0Education': [],
    'Biotech': [],
    'Birds': [],
    'Blogging': [],
    'Blues': [],
    'Bodybuilding': [],
    'Bollywood': [],
    'Books': [],
    'Books\xa0and\xa0Writing': ['Books',
                                'Poetry',
                                'Writing',
                                'Publishing',
                                'Screenwriting',
                                'Authors',
                                'Poetry Reading'],
    'Boxing': [],
    'Breaking\xa0Bad': [],
    'Breaking\xa0News': [],
    'Brethren': [],
    'Buddhist': [],
    'Buffy\xa0the\xa0Vampire\xa0Slayer': [],
    'Business\xa0Disciplines': ['Economics',
                                'Finance',
                                'Accounting',
                                'Law',
                                'Human Resources'],
    'Business\xa0Education': ['Architecture Education',
                              'Marketing Education',
                              'Accounting Education',
                              'Publishing Education',
                              'Real Estate Education',
                              'MBA Education'],
    'Business\xa0English': [],
    'Business\xa0News': ['Trading',
                         'Daily Business News',
                         'Business Trends',
                         'Money'],
    'Business\xa0Trends': [],
    'Cardiology': [],
    'Careers': [],
    'Castle': [],
    'Catechesis': [],
    'Catholic': [],
    'Cats': [],
    'Chemistry': [],
    'Chemistry\xa0Education': [],
    'Chess': [],
    'Chicago\xa0Cubs': [],
    'Chiropractic': [],
    'Christian': [],
    'Christianity': ['Catholic',
                     'Christian Apologetics',
                     'Christian Students',
                     'Mormon',
                     'Baptist',
                     'Methodist',
                     'Theology',
                     'Gospel Music',
                     'Catechesis',
                     'Bible Prophecy',
                     'Brethren',
                     'Protestant',
                     'Adventist',
                     'Salvation Army',
                     'Fellowship',
                     'Presbyterian',
                     'Apostolic',
                     'Lutheran',
                     'Christian Orthodox',
                     'Pentecostal',
                     'Community Church',
                     'Evangelical',
                     'Anglican'],
    'Christian\xa0Apologetics': [],
    'Christian\xa0Orthodox': [],
    'Christian\xa0Students': [],
    'Cinema': ['Bollywood',
               'Drama',
               'Crime',
               'Sci-Fi',
               'Fantasy',
               'Filmmaking',
               'Romance',
               'Soundtrack',
               'Superheroes',
               'Mystery',
               'Spy',
               'Animated Fiction',
               'Screenwriting',
               'Horror'],
    'Cinema\xa0Roundup': [],
    'Classical': [],
    'Classic\xa0Radio': [],
    'Classic\xa0Sitcoms': [],
    'Classic\xa0TV': ['Dragnet',
                      'The Twilight Zone',
                      'Gunsmoke',
                      'Classic Sitcoms'],
    'Classic\xa0TV\xa0Roundup': [],
    'Clean\xa0Comedy': [],
    'Climate\xa0Change': [],
    'Climbing': [],
    'Cloud\xa0IT': [],
    'Cloud\xa0IT\xa0Education': [],
    'Coaching': [],
    'Combat\xa0Sports': ['Boxing',
                         'Pro Wrestling',
                         'Martial Arts',
                         'MMA'],
    'Comedian\xa0Chat': [],
    'Comedian\xa0Interviews': [],
    'Comedy': ['Stand-up Comedy',
               'News Comedy',
               'Improv',
               'Mature Comedy',
               'Comedian Chat',
               'Sketch Comedy',
               'Clean Comedy',
               'Political Comedy',
               'Comedian Interviews'],
    'Comics': ['DC', 'Marvel'],
    'Comics\xa0Roundup': [],
    'Communities': ['Native American',
                    'Vegan',
                    'LGBT',
                    'African American',
                    'Military'],
    'Community\xa0Church': [],
    'Computer\xa0Science': [],
    'Conservative': [],
    'Conspiracy\xa0Theories': [],
    'Conversations': [],
    'Cosmetic\xa0Surgery': [],
    'Country': [],
    'Creativity': [],
    'Cricket': [],
    'Crime': ['Better Call Saul',
              'The Blacklist',
              'Sherlock Holmes',
              'Castle',
              'Alcatraz',
              'Dragnet',
              'Dexter',
              'Justified',
              'True Detective',
              'Breaking Bad'],
    'Cruising': [],
    'Current\xa0Affairs': [],
    'Current\xa0TV': ['American Horror Story',
                      'Arrow',
                      'Castle',
                      'Sleepy Hollow',
                      'Game of Thrones',
                      'Homeland',
                      'House of Cards',
                      'Walking Dead',
                      'The Young and the Restless',
                      'Modern Family',
                      'Downton Abbey',
                      'Scandal',
                      'The Americans',
                      'The Flash',
                      'Better Call Saul',
                      'The Blacklist',
                      'Falling Skies',
                      'Once Upon a Time',
                      'Vampire Diaries',
                      "Grey's Anatomy",
                      'True Detective',
                      'Westworld',
                      'Gotham',
                      'Supernatural',
                      'Pretty Little Liars'],
    'Cyber\xa0Currency': [],
    'Cycling': [],
    'DC': [],
    'Daily\xa0Business\xa0News': [],
    'Daily\xa0News': [],
    'Daily\xa0Tech\xa0News': [],
    'Dark\xa0Souls': [],
    'Darts': [],
    'Data\xa0Science': [],
    'Dating': [],
    'Dentistry': [],
    'Desperate\xa0Housewives': [],
    'Destiny': [],
    'DevOps': [],
    'Dexter': [],
    'Diabetes': [],
    'Digital\xa0Marketing': [],
    'Disc\xa0Golf': [],
    'Disney': [],
    'Doctor\xa0Who': [],
    'Documentaries': [],
    'Dogs': [],
    'Dollhouse': [],
    'DotA': [],
    'Downton\xa0Abbey': [],
    'Do\xa0It\xa0Yourself': [],
    'Dragnet': [],
    'Drama': ['Desperate Housewives',
              'Gunsmoke',
              'Sleepy Hollow',
              'The Following',
              'Secret Circle',
              'Rocky',
              'Terra Nova',
              'Gossip Girl',
              'Glee',
              'Justified',
              "Grey's Anatomy",
              'Soap Opera',
              'The Young and the Restless',
              'Gilmore Girls',
              'Last Resort',
              'Pretty Little Liars'],
    'Drones': [],
    'Drum\xa0and\xa0Bass': [],
    'Drupal': [],
    'Dungeons\xa0and\xa0Dragons': [],
    'E-Commerce': [],
    'E-Commerce\xa0Education': [],
    'Eclectic': [],
    'Economics': [],
    'Education\xa0Tech': [],
    'Electronic': [],
    'Elite:\xa0Dangerous': [],
    'Elvis\xa0Presley': [],
    'Emergency\xa0Medicine': [],
    'Endurance\xa0Sports': ['Cycling',
                            'Triathlon',
                            'Running',
                            'Swimming',
                            'Marathon'],
    'Energy': [],
    'Engineering': [],
    'English\xa0Pronunciation': [],
    'English\xa0Usage': [],
    'Entertainment\xa0Industry': ['Music Industry',
                                  'Filmmaking',
                                  'Showbiz'],
    'Entrepreneur': ['Tech Startups',
                     'Entrepreneur Lifestyle',
                     'Entrepreneur Interviews'],
    'Entrepreneur\xa0Interviews': [],
    'Entrepreneur\xa0Lifestyle': [],
    'Entrepreneur\xa0Roundup': [],
    'Environment': ['Greentech', 'Climate Change', 'Permaculture'],
    'Environment\xa0Roundup': [],
    'Equestrian': [],
    'Evangelical': [],
    'F1': [],
    'Facts\xa0and\xa0Trivia': [],
    'Falling\xa0Skies': [],
    'Family': [],
    'Fantasy': ['Twilight',
                'The Twilight Zone',
                'Harry Potter',
                'Secret Circle',
                'Once Upon a Time',
                'Vampire Diaries',
                'Lord of the Rings',
                'Game of Thrones',
                'Supernatural',
                'Buffy the Vampire Slayer',
                'True Blood'],
    'Fantasy\xa0American\xa0Football': [],
    'Fantasy\xa0Aussie\xa0Rules': [],
    'Fantasy\xa0Baseball': [],
    'Fantasy\xa0Basketball': [],
    'Fantasy\xa0Hockey': [],
    'Fantasy\xa0Soccer': [],
    'Fantasy\xa0Sports': ['Fantasy Hockey',
                          'Fantasy Basketball',
                          'Fantasy Soccer',
                          'Fantasy Baseball',
                          'Fantasy American Football',
                          'Fantasy Aussie Rules'],
    'Fantasy\xa0Sports\xa0Roundup': [],
    'Fascinating\xa0People': [],
    'Fashion\xa0and\xa0Beauty': [],
    'Fatherhood': [],
    'Fellowship': [],
    'Female\xa0Pop\xa0Singers': [],
    'Feminist': [],
    'Filmmaking': [],
    'Final\xa0Fantasy': [],
    'Finance': [],
    'Fine\xa0Arts': [],
    'Firefly': [],
    'Fish': [],
    'Fishing': [],
    'Fitness': ['Yoga',
                'Fitness Industry',
                'Bodybuilding',
                'Weightlifting',
                'Endurance Sports',
                'Strength Training',
                'Pilates'],
    'Fitness\xa0Industry': [],
    'Fitness\xa0Roundup': [],
    'Folk': [],
    'Food': [],
    'Food\xa0and\xa0Beverage': ['Food',
                                'Nutrition',
                                'Wine',
                                'Liquor',
                                'Beer',
                                'Whiskey'],
    'Football\xa0Manager': [],
    'Freelancing': [],
    'Fringe': [],
    'Future\xa0Trends': [],
    'Gadgets': [],
    'Gambling': [],
    'Games\xa0and\xa0Gambling': ['Poker',
                                 'Chess',
                                 'Pinball',
                                 'Sports Betting',
                                 'Darts',
                                 'Magic: The Gathering',
                                 'Table Top Games',
                                 'Fantasy Sports',
                                 'Horseracing',
                                 'Gambling'],
    'Game\xa0Development': [],
    'Game\xa0of\xa0Thrones': [],
    'Gardening': [],
    'Geekery': [],
    'Genealogy': [],
    'Genetics': [],
    'Geocaching': [],
    'Geography': [],
    'Geology': [],
    'Geology\xa0Education': [],
    'Gilmore\xa0Girls': [],
    'Glee': [],
    'Golf': [],
    'Gospel\xa0Music': [],
    'Gossip\xa0Girl': [],
    'Gotham': [],
    'Go\xa0To\xa0Sleep': [],
    'Graphic\xa0Design': [],
    'Greentech': [],
    'Green\xa0Lantern': [],
    "Grey's\xa0Anatomy": [],
    'Guitar': [],
    'Gunsmoke': [],
    'Harry\xa0Potter': [],
    'Health\xa0Care': ['Health Industry', 'Cosmetic Surgery'],
    'Health\xa0Industry': [],
    'Health\xa0News': [],
    'Hearthstone': [],
    'Heroes\xa0of\xa0the\xa0Storm': [],
    'Higher\xa0Education': [],
    'Hindu': [],
    'Hiphop': [],
    'History': [],
    'Hobbies': ['Knitting',
                'Drones',
                'Geocaching',
                'Motorcycle',
                'Climbing',
                'Sailing',
                'Do It Yourself',
                'Hunting',
                'Outdoor',
                'Painting',
                'Worldbuilding',
                'Auto',
                'Photography',
                'Fishing',
                'Quilting',
                'Gardening',
                'Woodworking',
                'Toys'],
    'Hockey': ['Fantasy Hockey', 'Toronto Maple Leafs'],
    'Hockey\xa0Roundup': [],
    'Holistic\xa0Health': [],
    'Homeland': [],
    'Homeschooling': [],
    'Horror': ['American Horror Story',
               'Sleepy Hollow',
               'Secret Circle',
               'The Strain',
               'Being Human',
               'Dexter',
               'Vampire Diaries',
               'Walking Dead',
               'X-Files',
               'Supernatural',
               'Buffy the Vampire Slayer',
               'True Blood'],
    'Horror\xa0Roundup': [],
    'Horror\xa0Stories': [],
    'Horseracing': [],
    'House\xa0of\xa0Cards': [],
    'Humanities\xa0Education': ['Archaeology Education',
                                'Linguistics Education'],
    'Human\xa0Resources': [],
    'Human\xa0Rights': [],
    'Humor': ['Desperate Housewives',
              'Gossip Girl',
              'Being Human',
              'Glee',
              'Classic Sitcoms',
              'Modern Family',
              'Gilmore Girls'],
    'Hunger\xa0Games': [],
    'Hunting': [],
    'Hypnosis': [],
    'IT\xa0Industry': ['E-Commerce',
                       'Drupal',
                       'Blogging',
                       'IT Management',
                       'Social Media',
                       'Animation',
                       'App Business',
                       'SEO',
                       'Wordpress',
                       'Podcasting',
                       'Tech Startups',
                       'Freelancing',
                       'Digital Marketing',
                       'Cloud IT'],
    'IT\xa0Management': [],
    'Immunology': [],
    'Improv': [],
    'Inclusive\xa0Education': [],
    'Indie\xa0Music': [],
    'Industries': ['Energy',
                   'Non-Profit',
                   'Real Estate',
                   'Engineering',
                   'Fitness Industry',
                   'Media',
                   'Publishing',
                   'Auto',
                   'Greentech',
                   'Agriculture',
                   'IT Industry',
                   'Health Industry',
                   'Entertainment Industry',
                   'Aviation',
                   'Architecture'],
    'Intellectual\xa0Property': [],
    'Interior\xa0Design': [],
    'International\xa0News': [],
    'International\xa0Relations': [],
    'Islamic': [],
    'J-pop': [],
    'J.R.R.\xa0Tolkien': [],
    'James\xa0Bond': [],
    'Java': [],
    'JavaScript': [],
    'Jazz': [],
    'Jewish': [],
    'Journalism': [],
    'Justified': [],
    'K-pop': [],
    'Kids\xa0and\xa0Family': ['Parenting',
                              'Family',
                              'Fatherhood',
                              'Motherhood'],
    'Knitting': [],
    'LGBT': [],
    'Language\xa0Learning': ['Learning Italian',
                             'Learning Chinese',
                             'Learning English',
                             'Learning Russian',
                             'Linguistics',
                             'Learning Japanese',
                             'Learning German',
                             'Learning French',
                             'Learning Hindi',
                             'Learning Portuguese',
                             'Learning Arabic',
                             'Learning Korean',
                             'Learning Spanish'],
    'Last\xa0Resort': [],
    'Latin\xa0Music': [],
    'Law': ['Intellectual Property'],
    'Law\xa0Roundup': [],
    'Leadership': [],
    'League\xa0of\xa0Legends': [],
    'Learning\xa0Arabic': [],
    'Learning\xa0Chinese': [],
    'Learning\xa0English': ['English Pronunciation',
                            'Business English',
                            'English Usage'],
    'Learning\xa0English\xa0Roundup': [],
    'Learning\xa0French': [],
    'Learning\xa0German': [],
    'Learning\xa0Hindi': [],
    'Learning\xa0Italian': [],
    'Learning\xa0Japanese': [],
    'Learning\xa0Korean': [],
    'Learning\xa0Portuguese': [],
    'Learning\xa0Russian': [],
    'Learning\xa0Spanish': [],
    'Libertarian': [],
    'Linguistics': [],
    'Linguistics\xa0Education': [],
    'Linux': [],
    'Linux\xa0Education': [],
    'Liquor': [],
    'Liverpool\xa0Football\xa0Club': [],
    'Lord\xa0of\xa0the\xa0Rings': [],
    'Lost': [],
    'Lutheran': [],
    'MBA': [],
    'MBA\xa0Education': [],
    'MMA': [],
    'MS\xa0Dev': [],
    'Mad\xa0Men': [],
    'Magic:\xa0The\xa0Gathering': [],
    'Manchester\xa0City\xa0Football\xa0Club': [],
    'Marathon': [],
    'Marketing': ['Sales', 'Digital Marketing', 'Public Relations'],
    'Marketing\xa0Education': [],
    'Marketing\xa0Roundup': [],
    'Marriage': [],
    'Martial\xa0Arts': [],
    'Marvel': [],
    'Math': [],
    'Math\xa0Education': [],
    'Mature\xa0Comedy': [],
    'Media': [],
    'Medicine': ['Oncology',
                 'Ophthalmology',
                 'Physical Therapy',
                 'Sports Medicine',
                 'Chiropractic',
                 'Immunology',
                 'Neurology',
                 'Psychiatry',
                 'Dentistry',
                 'Pharmacology',
                 'Anatomy',
                 'Cardiology',
                 'Emergency Medicine'],
    'Medicine\xa0Roundup': [],
    'Meditation': [],
    "Men's\xa0Corner": ["Men's Health"],
    "Men's\xa0Corner\xa0Roundup": [],
    "Men's\xa0Health": [],
    'Mental\xa0Health': ['Autism', "Alzheimer's Disease"],
    'Mental\xa0Health\xa0Roundup': [],
    'Metal': [],
    'Metaphysics': [],
    'Meteorology': [],
    'Methodist': [],
    'Michael\xa0Jackson': [],
    'Michigan\xa0Wolverines': [],
    'Military': ['Military History',
                 'US Veterans',
                 'US Military Family',
                 'US Military'],
    'Military\xa0History': [],
    'Minecraft': [],
    'Modern\xa0Family': [],
    'Money': [],
    'Mormon': [],
    'Motherhood': [],
    'Motorcycle': [],
    'Motorsports': ['F1', 'NASCAR'],
    'Motorsports\xa0Roundup': [],
    'Musicality': [],
    'Musicians': ['The Beatles',
                  'Female Pop Singers',
                  'Michael Jackson',
                  'Elvis Presley',
                  'Bands'],
    'Music\xa0Business': [],
    'Music\xa0Industry': ['Music Business',
                          'Musicality',
                          'Indie Music'],
    'Mystery': ['Sherlock Holmes',
                'Lost',
                'Castle',
                'Dragnet',
                'True Detective',
                'X-Files',
                'Supernatural',
                'Pretty Little Liars'],
    'Mythology': [],
    'NASCAR': [],
    'NBA': ['Oklahoma City Thunder'],
    'NBA\xa0Roundup': [],
    'Naruto': [],
    'Native\xa0American': [],
    'Natural\xa0Sciences': ['Oceanography',
                            'Physics',
                            'Biology',
                            'Genetics',
                            'Geography',
                            'Meteorology',
                            'Neuroscience',
                            'Biotech',
                            'Paleontology',
                            'Geology',
                            'Astronomy',
                            'Chemistry'],
    'Netrunner': [],
    'Neurology': [],
    'Neuroscience': [],
    'News\xa0Comedy': [],
    'News\xa0Talk': [],
    'News\xa0and\xa0Entertainment': [],
    'New\xa0Age': [],
    'New\xa0York\xa0Giants': [],
    'Nintendo': [],
    'Non-Profit': [],
    'Nutrition': ['Vegan', 'Paleo'],
    'Nutrition\xa0Roundup': [],
    'Oceanography': [],
    'Oklahoma\xa0City\xa0Thunder': [],
    'Oldies': [],
    'Once\xa0Upon\xa0a\xa0Time': [],
    'Oncology': [],
    'Open\xa0Source': [],
    'Operating\xa0Systems': ['Windows', 'Apple', 'Linux', 'Android'],
    'Ophthalmology': [],
    'Oracle': [],
    'Outdoor': [],
    'PC\xa0Gaming': [],
    'PHP': [],
    'Paganism': [],
    'Painting': [],
    'Paleo': [],
    'Paleontology': [],
    'Paranormal': [],
    'Parenting': [],
    'Pentecostal': [],
    'Period\xa0Drama': ['The Americans',
                        'Spartacus',
                        'Mad Men',
                        'Downton Abbey'],
    'Permaculture': [],
    'Personal\xa0Finances': [],
    'Pets': [],
    'Pharmacology': [],
    'Philosophy': [],
    'Photography': [],
    'Physical\xa0Therapy': [],
    'Physics': [],
    'Piano': [],
    'Pilates': [],
    'Pinball': [],
    'Pixar': [],
    'PlayStation': [],
    'Podcasting': [],
    'Podcasting\xa0Education': [],
    'Poetry': [],
    'Poetry\xa0Reading': [],
    'Pokemon': [],
    'Poker': [],
    'Political\xa0Comedy': [],
    'Political\xa0Drama': ['Homeland',
                           'Scandal',
                           'House of Cards',
                           'The West Wing',
                           'The Newsroom'],
    'Political\xa0Science': [],
    'Politics': ['Progressive',
                 'Libertarian',
                 'Political Science',
                 'International Relations',
                 'UK Politics',
                 'Conservative',
                 'Political Comedy',
                 'Activism',
                 'Law',
                 'US Government'],
    'Politics\xa0Roundup': [],
    'Pop': [],
    'Pop\xa0Culture': [],
    'Poultry': [],
    'Power\xa0Rangers': [],
    'Presbyterian': [],
    'Pretty\xa0Little\xa0Liars': [],
    'Productivity': [],
    'Programming': [],
    'Programming\xa0Education': [],
    'Progressive': [],
    'Prog\xa0Languages': ['JavaScript',
                          'Python',
                          'Java',
                          'Ruby',
                          'PHP'],
    'Prog\xa0Languages\xa0Roundup': [],
    'Project\xa0Management': [],
    'Protestant': [],
    'Pro\xa0Wrestling': [],
    'Psychiatry': [],
    'Psychic': [],
    'Psychology': [],
    'Psychology\xa0Education': [],
    'Public\xa0Relations': [],
    'Publishing': [],
    'Publishing\xa0Education': [],
    'Python': [],
    'Qigong\xa0And\xa0Tai\xa0Chi': [],
    'Quilting': [],
    'Reality\xa0TV': ['X Factor',
                      'The Bachelor',
                      'American Idol',
                      'The Real Housewives',
                      'Big Brother',
                      'Survivor'],
    'Reality\xa0TV\xa0Roundup': [],
    'Real\xa0Estate': [],
    'Real\xa0Estate\xa0Education': [],
    'Recent\xa0TV': ['Fringe',
                     'Spartacus',
                     'Dexter',
                     'X-Files',
                     'Last Resort',
                     'True Blood',
                     'Desperate Housewives',
                     'Mad Men',
                     'Lost',
                     'Secret Circle',
                     'Alcatraz',
                     'Smallville',
                     'Buffy the Vampire Slayer',
                     'Breaking Bad',
                     'The Following',
                     'Gossip Girl',
                     'Being Human',
                     'Glee',
                     'Firefly',
                     'Revolution',
                     'Dollhouse',
                     'Terra Nova',
                     'The Strain',
                     'Justified',
                     'The West Wing',
                     'Gilmore Girls',
                     'The Newsroom'],
    'Reggae': [],
    'Reiki': [],
    'Relationship': ['Marriage', 'Dating'],
    'Relationship\xa0Roundup': [],
    'Religion': ['Christianity',
                 'Atheism',
                 'Jewish',
                 'Buddhist',
                 'Alternative Spirituality',
                 'Islamic',
                 'Hindu'],
    'Religion\xa0Roundup': [],
    'Retro': ['Classic TV', 'Retro Gaming', 'Classic Radio'],
    'Retro\xa0Gaming': [],
    'Revolution': [],
    'Rock': [],
    'Rocky': [],
    'Romance': ['Twilight', 'Vampire Diaries'],
    'Ruby': [],
    'Rugby': [],
    'RuneScape': [],
    'Running': [],
    'SEO': [],
    'SEO\xa0Education': [],
    'Sailing': [],
    'Sailormoon': [],
    'Sales': [],
    'Salvation\xa0Army': [],
    'Scandal': [],
    'School\xa0Education': [],
    'Sci-Fi': ['Fringe',
               'The Twilight Zone',
               'Falling Skies',
               'Lost',
               'Revolution',
               'Dollhouse',
               'Star Trek',
               'Alcatraz',
               'Battlestar Galactica',
               'Doctor Who',
               'Smallville',
               'Terra Nova',
               'Stargate',
               'X-Files',
               'Star Wars',
               'Westworld',
               'Firefly',
               'Hunger Games'],
    'Sci-Fi\xa0/\xa0Fantasy\xa0Stories': [],
    'Sci-Fi\xa0Roundup': [],
    'Science\xa0Education': ['Geology Education',
                             'Math Education',
                             'Biology Education',
                             'Astronomy Education',
                             'Anatomy Education',
                             'Psychology Education',
                             'Anthropology Education',
                             'Chemistry Education',
                             'Sociology Education'],
    'Science\xa0Roundup': [],
    'Screenwriting': [],
    'Secret\xa0Circle': [],
    'Security': [],
    'Self-Help': ['Self-Improvement',
                  'Careers',
                  'Coaching',
                  'Leadership',
                  'Creativity',
                  'Productivity'],
    'Self-Improvement': [],
    'Serial': [],
    'Sexuality': [],
    'Shakespeare': [],
    'Shamanism': [],
    'Sherlock\xa0Holmes': [],
    'Short\xa0Stories': [],
    'Showbiz': [],
    'Skeptic': [],
    'Sketch\xa0Comedy': [],
    'Sleepy\xa0Hollow': [],
    'Smallville': [],
    'Soap\xa0Opera': [],
    'Soccer': ['Manchester City Football Club',
               'Fantasy Soccer',
               'Liverpool Football Club',
               'Arsenal Football Club',
               'Tottenham Hotspur Football Club'],
    'Soccer\xa0Roundup': [],
    'Social\xa0Media': [],
    'Social\xa0Media\xa0Education': [],
    'Social\xa0Sciences': ['Political Science',
                           'Sociology',
                           'Linguistics',
                           'Anthropology',
                           'Psychology',
                           'Philosophy',
                           'History',
                           'Archaeology',
                           'Metaphysics',
                           'Genealogy'],
    'Sociology': [],
    'Sociology\xa0Education': [],
    'Software\xa0Development': ['Prog Languages',
                                'Security',
                                'MS Dev',
                                'Data Science',
                                'Oracle',
                                'Agile',
                                'Programming',
                                'Game Development',
                                'User Experience',
                                'Graphic Design',
                                'Sysadmin',
                                'Computer Science',
                                'DevOps',
                                'Open Source',
                                'Web Development'],
    'Soul': [],
    'Soundtrack': [],
    'South\xa0America': [],
    'South\xa0Park': [],
    'Spartacus': [],
    'Specialized\xa0News': ['Showbiz',
                            'Sports News',
                            'Weather Alerts',
                            'Tech News'],
    'Spiritual\xa0Beings': [],
    'Sports\xa0Betting': [],
    'Sports\xa0Medicine': [],
    'Sports\xa0News': [],
    'Sports\xa0and\xa0Entertainment': [],
    'Spy': ['James Bond'],
    'Stand-up\xa0Comedy': [],
    'Stargate': [],
    'Star\xa0Trek': [],
    'Star\xa0Wars': [],
    'Strength\xa0Training': [],
    'Superheroes': ['Power Rangers',
                    'Marvel',
                    'Arrow',
                    'Transformers',
                    'Smallville',
                    'Green Lantern',
                    'DC',
                    'Gotham',
                    'Superman',
                    'Batman',
                    'The Flash'],
    'Superman': [],
    'Supernatural': [],
    'Survivor': [],
    'Swimming': [],
    'Sysadmin': [],
    'TV': ['Drama',
           'Crime',
           'Recent TV',
           'Sci-Fi',
           'Fantasy',
           'Period Drama',
           'Current TV',
           'Superheroes',
           'Mystery',
           'Spy',
           'Reality TV',
           'Animated Fiction',
           'Political Drama',
           'Classic TV',
           'Horror',
           'Humor'],
    'TV\xa0Roundup': [],
    'Table\xa0Top\xa0Games': ['Netrunner'],
    'Table\xa0Top\xa0Games\xa0Roundup': [],
    'Tarot': [],
    'Taxation': [],
    'Teaching': ['Higher Education',
                 'Homeschooling',
                 'Teaching Trends',
                 'Education Tech',
                 'Inclusive Education',
                 'School Education'],
    'Teaching\xa0Trends': [],
    'Tech\xa0Education': ['Podcasting Education',
                          'Programming Education',
                          'Cloud IT Education',
                          'SEO Education',
                          'App Business Education',
                          'Social Media Education',
                          'E-Commerce Education',
                          'Linux Education',
                          'Web Development Education'],
    'Tech\xa0News': [],
    'Tech\xa0Startups': [],
    'Tech\xa0Tips': [],
    'Tennis': [],
    'Terra\xa0Nova': [],
    'Theater': [],
    'Theme\xa0Parks': [],
    'Theology': [],
    'The\xa0Americans': [],
    'The\xa0Bachelor': [],
    'The\xa0Beatles': [],
    'The\xa0Blacklist': [],
    'The\xa0Elder\xa0Scrolls': [],
    'The\xa0Flash': [],
    'The\xa0Following': [],
    'The\xa0Newsroom': [],
    'The\xa0Real\xa0Housewives': [],
    'The\xa0Simpsons': [],
    'The\xa0Strain': [],
    'The\xa0Twilight\xa0Zone': [],
    'The\xa0West\xa0Wing': [],
    'The\xa0Young\xa0and\xa0the\xa0Restless': [],
    'Toronto\xa0Blue\xa0Jays': [],
    'Toronto\xa0Maple\xa0Leafs': [],
    'Tottenham\xa0Hotspur\xa0Football\xa0Club': [],
    'Toys': [],
    'Trading': [],
    'Transformers': [],
    'Travel': ['Cruising', 'Theme Parks', 'South America'],
    'Travel\xa0Roundup': [],
    'Triathlon': [],
    'True\xa0Blood': [],
    'True\xa0Crime': ['Serial'],
    'True\xa0Crime\xa0Roundup': [],
    'True\xa0Detective': [],
    'True\xa0Stories': [],
    'Twilight': [],
    'UFOs': [],
    'UK\xa0Politics': [],
    'US\xa0Government': [],
    'US\xa0Military': [],
    'US\xa0Military\xa0Family': [],
    'US\xa0Veterans': [],
    'Ukulele': [],
    'Unitarian\xa0Universalist': [],
    'Urban\xa0Survival': [],
    'User\xa0Experience': [],
    'Vampire\xa0Diaries': [],
    'Varsity\xa0Teams': ['Michigan Wolverines', 'Arkansas Razorbacks'],
    'Vegan': [],
    'Venture\xa0Capital': [],
    'Video\xa0Games': ['Retro Gaming',
                       'Destiny',
                       'Minecraft',
                       'Xbox',
                       'Heroes of the Storm',
                       'Warhammer',
                       'The Elder Scrolls',
                       'Football Manager',
                       'Dark Souls',
                       'RuneScape',
                       'Hearthstone',
                       'World of Warcraft',
                       'Nintendo',
                       'Elite: Dangerous',
                       'DotA',
                       'League of Legends',
                       'Final Fantasy',
                       'Dungeons and Dragons',
                       'PlayStation',
                       'Game Development',
                       'Arcade Games',
                       'Video Game Music',
                       'PC Gaming'],
    'Video\xa0Games\xa0Roundup': [],
    'Video\xa0Game\xa0Music': [],
    'Walking\xa0Dead': [],
    'Warhammer': [],
    'Washington\xa0Redskins': [],
    'Weather\xa0Alerts': [],
    'Web\xa0Development': [],
    'Web\xa0Development\xa0Education': [],
    'Weightlifting': [],
    'Westworld': [],
    'Whiskey': [],
    'Windows': [],
    'Wine': [],
    "Women's\xa0Corner": ["Women's Health"],
    "Women's\xa0Corner\xa0Roundup": [],
    "Women's\xa0Health": [],
    'Woodworking': [],
    'Wordpress': [],
    'Worldbuilding': [],
    'World\xa0of\xa0Warcraft': [],
    'Writing': [],
    'X-Files': [],
    'Xbox': [],
    'X\xa0Factor': [],
    'Yoga': []
}

with open('playfm_data.txt', 'w') as fh:
    for t in tags:
        fh.write('- %s\n' % t)
        for sub_t in tags[t]:
            fh.write('    - %s\n' % sub_t)
