# ---------- common options ----------
# in case job failed or not scheduled.
nsched.submit-retry=2
nsched.no-retry-file=/tmp/NSCHED_NO_RETRY
nsched.notify.no-report-file=/tmp/NSCHED_NO_REPORT
# 15 minutes. won't send a lot of mails or sms.
nsched.notify.interval=900
#dpsubmit2.et2 10.181.42.13
nsched.notify.host=10.181.42.13
nsched.notify.port=57004
nsched.notify.enable=1

# database config
nsched.db-name=nsched_dp
nsched.db-host=localhost
nsched.redis-host=10.181.42.13

# nsched server port
nsched.http-host=0.0.0.0
nsched.http-port=8000
# nsched log dir
nsched.log-dir=logs
nsched.max-fetch-log-size=32768

# ---------- uncommon options ----------
# most time you don't ned to change them.
nsched.coord-loop-interval=10
nsched.task-thread-number=128
nsched.task-queue-size=256
nsched.task-queue-timeout=2000
nsched.http-page-refresh-interval=-1

nsched.sms-alert.host=10.181.42.13
nsched.sms-alert.port=50000
nsched.sms-alert.expire=30
